/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PackageModel } from "./PackageModel";
import { PackageModelCountArgs } from "./PackageModelCountArgs";
import { PackageModelFindManyArgs } from "./PackageModelFindManyArgs";
import { PackageModelFindUniqueArgs } from "./PackageModelFindUniqueArgs";
import { DeletePackageModelArgs } from "./DeletePackageModelArgs";
import { PackageModelService } from "../packageModel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PackageModel)
export class PackageModelResolverBase {
  constructor(
    protected readonly service: PackageModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PackageModel",
    action: "read",
    possession: "any",
  })
  async _packageModelsMeta(
    @graphql.Args() args: PackageModelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PackageModel])
  @nestAccessControl.UseRoles({
    resource: "PackageModel",
    action: "read",
    possession: "any",
  })
  async packageModels(
    @graphql.Args() args: PackageModelFindManyArgs
  ): Promise<PackageModel[]> {
    return this.service.packageModels(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PackageModel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PackageModel",
    action: "read",
    possession: "own",
  })
  async packageModel(
    @graphql.Args() args: PackageModelFindUniqueArgs
  ): Promise<PackageModel | null> {
    const result = await this.service.packageModel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PackageModel)
  @nestAccessControl.UseRoles({
    resource: "PackageModel",
    action: "delete",
    possession: "any",
  })
  async deletePackageModel(
    @graphql.Args() args: DeletePackageModelArgs
  ): Promise<PackageModel | null> {
    try {
      return await this.service.deletePackageModel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
