/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Credit } from "./Credit";
import { CreditCountArgs } from "./CreditCountArgs";
import { CreditFindManyArgs } from "./CreditFindManyArgs";
import { CreditFindUniqueArgs } from "./CreditFindUniqueArgs";
import { DeleteCreditArgs } from "./DeleteCreditArgs";
import { CreditService } from "../credit.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Credit)
export class CreditResolverBase {
  constructor(
    protected readonly service: CreditService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Credit",
    action: "read",
    possession: "any",
  })
  async _creditsMeta(
    @graphql.Args() args: CreditCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Credit])
  @nestAccessControl.UseRoles({
    resource: "Credit",
    action: "read",
    possession: "any",
  })
  async credits(@graphql.Args() args: CreditFindManyArgs): Promise<Credit[]> {
    return this.service.credits(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Credit, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Credit",
    action: "read",
    possession: "own",
  })
  async credit(
    @graphql.Args() args: CreditFindUniqueArgs
  ): Promise<Credit | null> {
    const result = await this.service.credit(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Credit)
  @nestAccessControl.UseRoles({
    resource: "Credit",
    action: "delete",
    possession: "any",
  })
  async deleteCredit(
    @graphql.Args() args: DeleteCreditArgs
  ): Promise<Credit | null> {
    try {
      return await this.service.deleteCredit(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
